# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - container-kms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crmsk.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FF57CEB39A094AF09683292342C3A2C4 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_37DFA206A98242C18275DF78D64A3FFF }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crmsk.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FF57CEB39A094AF09683292342C3A2C4 }}/guestbook-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'container-kms'
          slot-name: 'Production'
          images: 'crmsk.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_FF57CEB39A094AF09683292342C3A2C4 }}/guestbook-app:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D7084F405C9D4AF581FA97DFB8A0CB38 }}